#pragma once

#define WEAPON_DEAGLE 1
#define    WEAPON_ELITE 2 
#define       WEAPON_FIVESEVEN 3
#define       WEAPON_GLOCK   4 
#define       WEAPON_AK47   7 
#define      WEAPON_AUG   8 
#define      WEAPON_AWP   9 
#define      WEAPON_FAMAS   10 
#define     WEAPON_G3SG1   11 
#define    WEAPON_GALILAR   13 
#define    WEAPON_M249   14 
#define    WEAPON_M4A1   16 
#define     WEAPON_MAC10   17 
#define      WEAPON_P90   19 
#define     WEAPON_UMP45   24 
#define    WEAPON_XM1014   25 
#define    WEAPON_BIZON   26 
#define      WEAPON_MAG7   27 
#define     WEAPON_NEGEV   28 
#define      WEAPON_SAWEDOFF   29 
#define     WEAPON_TEC9   30 
#define     WEAPON_TASER   31 
#define     WEAPON_HKP2000   32 
#define     WEAPON_MP7   33 
#define      WEAPON_MP9   34 
#define     WEAPON_NOVA   35 
#define     WEAPON_P250   36 
#define      WEAPON_SCAR20   38 
#define      WEAPON_SG556   39 
#define      WEAPON_SSG08   40 
#define      WEAPON_KNIFE   42 
#define      WEAPON_FLASHBANG   43 
#define       WEAPON_HEGRENADE   44 
#define     WEAPON_SMOKEGRENADE   45 
#define     WEAPON_MOLOTOV   46 
#define       WEAPON_DECOY   47 
#define       WEAPON_INCGRENADE   48 
#define      WEAPON_C4   49 
#define      WEAPON_KNIFE_T   59 
#define       WEAPON_M4A1_SILENCER   60 
#define      WEAPON_USP_SILENCER   61 
#define		WEAPON_CZ75A 63
#define		 WEAPON_REVOLVER 64
#define		 WEAPON_KNIFE_BAYONET 500
#define		  WEAPON_KNIFE_FLIP   505 
#define		 WEAPON_KNIFE_GUT   506 
#define		  WEAPON_KNIFE_KARAMBIT   507 
#define		  WEAPON_KNIFE_M9_BAYONET   508 
#define		  WEAPON_KNIFE_TACTICAL   509 
#define				   WEAPON_KNIFE_FALCHION   512 
#define		  WEAPON_KNIFE_SURVIVAL_BOWIE   514 
#define		   WEAPON_KNIFE_BUTTERFLY   515 
#define			 WEAPON_KNIFE_PUSH   516;
